# Машинное обучение

Удалим все переменные, которые не понадобятся в машинном обучении: информация о 'geo_lat', 'geo_lon', 'diff_lat' и 'diff_lon' содержится в переменной 'gap', а о 'postal_code' - в переменной 'district'. 

In [69]:
our_df2.drop(['geo_lat', 'geo_lon', 'diff_lat', 'diff_lon', 'postal_code'], axis=1, inplace=True)
our_df2

date     price  floor  n_floors  rooms  area  kitchen_area  \
4     2021-01-01  25173570     19        22      2  90.5           0.0   
6     2021-01-01   6418000     21        32     -1  20.0           5.0   
7     2021-01-01  21000000      4        18      4  92.9          12.0   
9     2021-01-01  11750000     17        17      3  76.6          11.0   
11    2021-01-01  11000000      2         9      3  55.1           6.0   
...          ...       ...    ...       ...    ...   ...           ...   
38196 2021-02-15  15500000      7        17      2  58.0          10.0   
38198 2021-02-15  13500000      1         5      1  47.2          10.0   
38200 2021-02-15  18500000     10        14      2  53.0           9.0   
38201 2021-02-15   8100000      7         9      2  44.8           6.0   
38203 2021-02-15  19800000      3         9      2  44.2           0.0   

       object_type        gap district  
4                2  11.039047      ЗАО  
6                2  11.864770      ВАО  
7                0  17.906452     ЮВАО  
9                0  18.752424     ЮВАО  
11               0  17.394805      ВАО  
...            ...        ...      ...  
38196            0  22.291040      ЗАО  
38198            0   5.146934      ЦАО  
38200            0   8.618141     СВАО  
38201            0  19.853448     ЮВАО  
38203            0   5.939567      ЗАО  

[23638 rows x 10 columns]

In [70]:
our_df2.reset_index(drop=True, inplace=True)

Так как переменная object_type и так принимает всего два значения, мы с помощью цикла переведем ее в категориальную (2 поменяем на 1).

In [71]:
for i in range(23638):
    if our_df2['object_type'][i] == 2:
        
        our_df2['object_type'][i] = 1
        
our_df2

date     price  floor  n_floors  rooms  area  kitchen_area  \
0     2021-01-01  25173570     19        22      2  90.5           0.0   
1     2021-01-01   6418000     21        32     -1  20.0           5.0   
2     2021-01-01  21000000      4        18      4  92.9          12.0   
3     2021-01-01  11750000     17        17      3  76.6          11.0   
4     2021-01-01  11000000      2         9      3  55.1           6.0   
...          ...       ...    ...       ...    ...   ...           ...   
23633 2021-02-15  15500000      7        17      2  58.0          10.0   
23634 2021-02-15  13500000      1         5      1  47.2          10.0   
23635 2021-02-15  18500000     10        14      2  53.0           9.0   
23636 2021-02-15   8100000      7         9      2  44.8           6.0   
23637 2021-02-15  19800000      3         9      2  44.2           0.0   

       object_type        gap district  
0                1  11.039047      ЗАО  
1                1  11.864770      ВАО  
2                0  17.906452     ЮВАО  
3                0  18.752424     ЮВАО  
4                0  17.394805      ВАО  
...            ...        ...      ...  
23633            0  22.291040      ЗАО  
23634            0   5.146934      ЦАО  
23635            0   8.618141     СВАО  
23636            0  19.853448     ЮВАО  
23637            0   5.939567      ЗАО  

[23638 rows x 10 columns]

In [72]:
our_df2 = pd.get_dummies(our_df2, drop_first=True) # ко всем object применится OHE
our_df2

date     price  floor  n_floors  rooms  area  kitchen_area  \
0     2021-01-01  25173570     19        22      2  90.5           0.0   
1     2021-01-01   6418000     21        32     -1  20.0           5.0   
2     2021-01-01  21000000      4        18      4  92.9          12.0   
3     2021-01-01  11750000     17        17      3  76.6          11.0   
4     2021-01-01  11000000      2         9      3  55.1           6.0   
...          ...       ...    ...       ...    ...   ...           ...   
23633 2021-02-15  15500000      7        17      2  58.0          10.0   
23634 2021-02-15  13500000      1         5      1  47.2          10.0   
23635 2021-02-15  18500000     10        14      2  53.0           9.0   
23636 2021-02-15   8100000      7         9      2  44.8           6.0   
23637 2021-02-15  19800000      3         9      2  44.2           0.0   

       object_type        gap  district_ЗАО  district_САО  district_СВАО  \
0                1  11.039047             1             0              0   
1                1  11.864770             0             0              0   
2                0  17.906452             0             0              0   
3                0  18.752424             0             0              0   
4                0  17.394805             0             0              0   
...            ...        ...           ...           ...            ...   
23633            0  22.291040             1             0              0   
23634            0   5.146934             0             0              0   
23635            0   8.618141             0             0              1   
23636            0  19.853448             0             0              0   
23637            0   5.939567             1             0              0   

       district_СЗАО  district_ЦАО  district_ЮАО  district_ЮВАО  district_ЮЗАО  
0                  0             0             0              0              0  
1                  0             0             0              0              0  
2                  0             0             0              1              0  
3                  0             0             0              1              0  
4                  0             0             0              0              0  
...              ...           ...           ...            ...            ...  
23633              0             0             0              0              0  
23634              0             1             0              0              0  
23635              0             0             0              0              0  
23636              0             0             0              1              0  
23637              0             0             0              0              0  

[23638 rows x 17 columns]

In [73]:
our_df2.drop(['date'], axis=1, inplace=True)
our_df2

price  floor  n_floors  rooms  area  kitchen_area  object_type  \
0      25173570     19        22      2  90.5           0.0            1   
1       6418000     21        32     -1  20.0           5.0            1   
2      21000000      4        18      4  92.9          12.0            0   
3      11750000     17        17      3  76.6          11.0            0   
4      11000000      2         9      3  55.1           6.0            0   
...         ...    ...       ...    ...   ...           ...          ...   
23633  15500000      7        17      2  58.0          10.0            0   
23634  13500000      1         5      1  47.2          10.0            0   
23635  18500000     10        14      2  53.0           9.0            0   
23636   8100000      7         9      2  44.8           6.0            0   
23637  19800000      3         9      2  44.2           0.0            0   

             gap  district_ЗАО  district_САО  district_СВАО  district_СЗАО  \
0      11.039047             1             0              0              0   
1      11.864770             0             0              0              0   
2      17.906452             0             0              0              0   
3      18.752424             0             0              0              0   
4      17.394805             0             0              0              0   
...          ...           ...           ...            ...            ...   
23633  22.291040             1             0              0              0   
23634   5.146934             0             0              0              0   
23635   8.618141             0             0              1              0   
23636  19.853448             0             0              0              0   
23637   5.939567             1             0              0              0   

       district_ЦАО  district_ЮАО  district_ЮВАО  district_ЮЗАО  
0                 0             0              0              0  
1                 0             0              0              0  
2                 0             0              1              0  
3                 0             0              1              0  
4                 0             0              0              0  
...             ...           ...            ...            ...  
23633             0             0              0              0  
23634             1             0              0              0  
23635             0             0              0              0  
23636             0             0              1              0  
23637             0             0              0              0  

[23638 rows x 16 columns]

### Для начала попробуем обычную модель линейной регрессии для датафрейма our_df2.

In [74]:
from sklearn.model_selection import train_test_split 

# делим в пропорции 80 к 20
df_train, df_test = train_test_split(our_df2, test_size = 0.2, random_state=42)

In [75]:
y_train = df_train['price'].to_numpy()
y_test = df_test['price'].to_numpy()

X_train = df_train.drop('price', axis=1).to_numpy()
X_test = df_test.drop('price', axis=1).to_numpy()



In [76]:
from sklearn.linear_model import LinearRegression

model_regression = LinearRegression()
 
model_regression.fit(X_train, y_train)
y_pred = model_regression.predict(X_test)

In [77]:
model_regression.coef_ 

array([ 1.52443921e+05, -5.56854510e+05, -9.74515248e+06,  8.89382264e+05,
        1.13345072e+04, -1.54802990e+06, -3.42970050e+05, -3.28313906e+06,
       -3.92130005e+06, -4.53400881e+06, -2.02097972e+06,  1.76775241e+07,
       -2.30263108e+06, -1.64603592e+06, -3.05989053e+06])

In [78]:
model_regression.intercept_

-3240753.3917960487

In [79]:
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

In [80]:
mean_squared_error(y_test, y_pred), mean_absolute_error(y_test, y_pred), r2_score(y_test, y_pred)

(1377893546305200.2, 13870656.883429538, 0.6138849065939385)

In [81]:
from sklearn.metrics import mean_absolute_percentage_error
mean_absolute_percentage_error(y_test, y_pred)

0.6375237525282295

Видим, что значения коэффициентов и метрик очень большие. Попробуем применить другой вид регрессии и поработать с данными, чтобы улучшить качество модели. 

### Начнем со стандартизации значений, применив StandardScaler.

In [82]:
from sklearn.preprocessing import StandardScaler #отскалируем (нормализуем) данные 

scaler = StandardScaler()


our_df3 = scaler.fit_transform(our_df2[['floor', 'n_floors', 'rooms', 'area', 'kitchen_area', 'gap']])
our_df4 = pd.DataFrame(our_df3, columns = [['floor', 'n_floors', 'rooms', 'area', 'kitchen_area', 'gap']])

In [84]:
our_df5 = pd.merge(our_df4, our_df2[['object_type', 'district_ЗАО', 'district_САО', 'district_СВАО', 'district_СЗАО', 'district_ЦАО', 'district_ЮАО', 'district_ЮВАО', 'district_ЮЗАО']], left_index=True, right_index=True)
our_df5

(floor,)  (n_floors,)  (rooms,)   (area,)  (kitchen_area,)    (gap,)  \
0      1.387298     0.496297 -0.081725  0.368492         0.192861 -0.498080   
1      1.655977     1.528570 -2.430909 -1.039794         0.318289 -0.361130   
2     -0.627795     0.083388  1.484398  0.416434         0.493890  0.640915   
3      1.118619    -0.019839  0.701337  0.090830         0.468804  0.781223   
4     -0.896474    -0.845657  0.701337 -0.338647         0.343375  0.556055   
...         ...          ...       ...       ...              ...       ...   
23633 -0.224776    -0.019839 -0.081725 -0.280718         0.443718  1.368121   
23634 -1.030813    -1.258567 -0.864786 -0.496455         0.443718 -1.475318   
23635  0.178242    -0.329521 -0.081725 -0.380596         0.418632 -0.899600   
23636 -0.224776    -0.845657 -0.081725 -0.544397         0.343375  0.963834   
23637 -0.762134    -0.845657 -0.081725 -0.556382         0.192861 -1.343855   

       object_type  district_ЗАО  district_САО  district_СВАО  district_СЗАО  \
0                1             1             0              0              0   
1                1             0             0              0              0   
2                0             0             0              0              0   
3                0             0             0              0              0   
4                0             0             0              0              0   
...            ...           ...           ...            ...            ...   
23633            0             1             0              0              0   
23634            0             0             0              0              0   
23635            0             0             0              1              0   
23636            0             0             0              0              0   
23637            0             1             0              0              0   

       district_ЦАО  district_ЮАО  district_ЮВАО  district_ЮЗАО  
0                 0             0              0              0  
1                 0             0              0              0  
2                 0             0              1              0  
3                 0             0              1              0  
4                 0             0              0              0  
...             ...           ...            ...            ...  
23633             0             0              0              0  
23634             1             0              0              0  
23635             0             0              0              0  
23636             0             0              1              0  
23637             0             0              0              0  

[23638 rows x 15 columns]

In [85]:
our_df6 = pd.merge(our_df5, our_df2[['price']], left_index=True, right_index=True)
#  our_df6

In [86]:

# делим в пропорции 80 к 20
df_train, df_test = train_test_split(our_df6, test_size = 0.2, random_state=42)

y_train = df_train['price'].to_numpy()
y_test = df_test['price'].to_numpy()

X_train = df_train.drop('price', axis=1).to_numpy()
X_test = df_test.drop('price', axis=1).to_numpy()

from sklearn.linear_model import LinearRegression 
model_regression = LinearRegression()


model_regression.fit(X_train, y_train)
 
y_pred = model_regression.predict(X_test)

In [87]:
model_regression.coef_ 

array([  1134766.00657729,  -5394451.44381657, -12444940.23673061,
        44523213.12925376,    451830.41730013,  -2067888.56460271,
        -1548029.90075058,  -3283139.06346085,  -3921300.04753783,
        -4534008.81214284,  -2020979.72095047,  17677524.06994531,
        -2302631.07566212,  -1646035.91788027,  -3059890.5338977 ])

In [88]:
model_regression.intercept_

27179961.314211752

In [89]:
mean_squared_error(y_test, y_pred), mean_absolute_error(y_test, y_pred), r2_score(y_test, y_pred)

(1377893546305198.2, 13870656.883429587, 0.6138849065939391)

In [90]:
mean_absolute_percentage_error(y_test, y_pred)

0.6375237525282322

Значения коэффициентов уменьшились, но метрики все еще показывают плохое качество модели. 

### Попробуем применить Lasso и Ridge регрессии и посмотрим, есть ли изменения.

In [91]:
from sklearn.linear_model import Lasso

model = Lasso(alpha=200)

model.fit(X_train, y_train)
y_pred = model.predict(X_test)


In [92]:
model.coef_

array([  1134201.25646619,  -5394327.49397854, -12443921.53220077,
        44522202.78573978,    451612.26344839,  -2067341.94752101,
        -1546811.9809373 ,  -3271750.24354394,  -3909631.22284382,
        -4521963.70555529,  -2006587.41668024,  17687735.87911611,
        -2289709.23231137,  -1633502.43502535,  -3044059.26341389])

In [93]:
model.intercept_

27169139.760130964

In [94]:
mean_squared_error(y_test, y_pred), mean_absolute_error(y_test, y_pred), r2_score(y_test, y_pred)

(1377907017597333.8, 13870340.319131557, 0.613881131651212)

In [95]:
mean_absolute_percentage_error(y_test, y_pred)

0.6374910469957983

In [96]:
from sklearn.linear_model import Ridge

model = Ridge(alpha=200) 

model.fit(X_train, y_train)
y_pred = model.predict(X_test)


In [97]:
model.coef_

array([  1046500.82994291,  -5245187.4944571 , -11383386.14321538,
        43268797.71251725,    384283.63488312,  -2531030.03214664,
        -1535755.41543653,  -2515656.78193105,  -3702072.1765831 ,
        -4319780.48980881,  -1438580.75102622,  16501775.56729578,
        -1977637.41309607,  -1430949.44951832,  -2406327.00422639])

In [98]:
model.intercept_

27075057.969625514

In [99]:
mean_squared_error(y_test, y_pred), mean_absolute_error(y_test, y_pred), r2_score(y_test, y_pred)

(1390833622588007.5, 13628715.530518292, 0.6102588218532012)

In [100]:
from sklearn.metrics import mean_absolute_percentage_error
mean_absolute_percentage_error(y_test, y_pred)

0.6171240167581463

Видим, что значения метрик немного лучше, чем в предыдущих, однако наша модель ошибается в среднем на 60%. Мы подумали, что большое кол-во колонок может мешать обучению модели, а информация о районе может быть отображена в колонке gap.

### МО без переменной district

In [101]:
our_df2.drop(['district_ЗАО', 'district_САО', 'district_СВАО', 'district_СЗАО', 'district_ЦАО', 'district_ЮАО', 'district_ЮВАО', 'district_ЮЗАО'], axis = 1, inplace = True)
#  our_df2

In [102]:
from sklearn.model_selection import train_test_split 

# делим в пропорции 80 к 20
df_train, df_test = train_test_split(our_df2, test_size = 0.2, random_state=42)

In [103]:
y_train = df_train['price'].to_numpy()
y_test = df_test['price'].to_numpy()

X_train = df_train.drop('price', axis=1).to_numpy()
X_test = df_test.drop('price', axis=1).to_numpy()

In [104]:
from sklearn.linear_model import LinearRegression
model_regression = LinearRegression()
 
model_regression.fit(X_train, y_train)

y_pred = model_regression.predict(X_test)

In [105]:
model_regression.coef_ 

array([ 1.11666901e+05, -5.56867144e+05, -1.00206792e+07,  9.16819549e+05,
        8.21882793e+03, -2.40502016e+06, -9.29788535e+05])

In [106]:
model_regression.intercept_

4626925.128027134

In [107]:
from sklearn.metrics import mean_absolute_percentage_error
mean_absolute_percentage_error(y_test, y_pred)

0.6635114986317856

Lasso:

In [108]:
from sklearn.linear_model import Lasso

model = Lasso(alpha=200)

model.fit(X_train, y_train)
y_pred = model.predict(X_test)


In [109]:
model.coef_

array([ 1.11652023e+05, -5.56878722e+05, -1.00203802e+07,  9.16814229e+05,
        8.22282037e+03, -2.40346849e+06, -9.29780890e+05])

In [110]:
model_regression.intercept_

4626925.128027134

In [111]:
from sklearn.metrics import mean_absolute_percentage_error
mean_absolute_percentage_error(y_test, y_pred)

0.6635074636711162

Ridge:

In [113]:
from sklearn.linear_model import Ridge

model = Ridge(alpha=200) 

model.fit(X_train, y_train)
y_pred = model.predict(X_test)


In [114]:
model.intercept_

4515255.318547353

In [115]:
model.coef_

array([ 1.10104978e+05, -5.58265969e+05, -9.87132776e+06,  9.14005966e+05,
        8.35665758e+03, -2.22031859e+06, -9.29822365e+05])

In [116]:
mean_squared_error(y_test, y_pred), mean_absolute_error(y_test, y_pred), r2_score(y_test, y_pred)

(1430158445108598.8, 14145319.704593247, 0.5992391697462367)

In [117]:
from sklearn.metrics import mean_absolute_percentage_error
mean_absolute_percentage_error(y_test, y_pred)

0.6618789437300623

К сожалению, удаление дамми-переменных только ухудшило и без того плохое качество модели. Это логично, так как переменная gap отражает только расстояние, которое может откладываться в любую сторону от центра, то есть на самом деле она не содержит информацию об округе. На данном этапе мы не знаем, как улучшить нашу модель, но это означает лишь то, что у проекта есть потенциал для дальнейшего развития.

## Послесловие:

Нам кажется, что рассматривать зависимость цены на квартиру от округа Москвы, в котором она расположена, не совсем корректно, потому что даже внутри одного округа цены на квартиры распределены неравномерно: в зависимости от разных инфраструктурных и экологических факторов. Для более точных результатов нужно проводить анализ с помощью кластеризации более мелких территориальных единиц (например, районов) по совокупности таких факторов, как наличие поликлиник/школ/детских садов вблизи дома, уровень загрязненности воздуха (близость к промышленным предприятиям), тип застройки, возраст дома, наличие развлекательной инфраструктуры. 

Данную информацию мы узнали из презентации магистерской работы на лекции по теории вероятностей. 